# This is the default configuration.
# Best practice is to copy this file to config.yaml before editing
# DomotiPi will automatically load config.yaml in favor of config-default.yaml

#######################################################################################################################
# GPIO settings
#######################################################################################################################
# The GPIO settings are configured here.
#
# The default factory is lgpio, for use on bare metal.
#
# In case you want to run DomotiPi from a control machine thus controlling the device remotely, pigpio can be used.
# This also requires you to configure more variables, like the host.
#
# Probably all factories are supported, but currently only lgpio and pigpio are tested.
# See: https://gpiozero.readthedocs.io/en/stable/api_pins.html#
pin_factory: lgpio
#pin_factory: pigpio
#pigpio_addr: 127.0.0.1


#######################################################################################################################
# MQTT settings
#######################################################################################################################
# Enter the details of your MQTT broker below,
#
# HINT: for HASS users: new users are preferably created through HASS user management
#

# MQTT settings
mqtt:
  # Topic prefix. Examples: homeassistant, livingroom
  topic_prefix: homeassistant

  # Broker settings
  host:
    hostname: 192.168.1.1
    port: 1883

# Client settings
  client:
    client_id: homeassistant_client
    username: homeassistant
    password: password


#######################################################################################################################
# Device configuration
#######################################################################################################################
# All devices can optionally be configured here instead of manual instantiation with the required arguments.
# Default settings can be overridden on a per-device level.
# GPIO settings are configured on a per-device level.
#
# NOTE: device configuration is likely to be moved
# NOTE: device setup through config files will possibly become mandatory
devices:
  default:
    manufacturer: DomotiPi Devices GPLv3
    model: DomotiPi Device
    hardware_version: 0.1.3.0  # Misuse DomotiPi version as hardware version
    software_version: 0.1.3.0
    support_URL: https://github.com/maghiel/domotipi
    suggested_area: living_room
  1:
    id: 1
    type: Light.Light
    name: Light
    description: Base Light class
    service: None
    manufacturer: Your mom
  5:
    id: 9999
    type: Light.LED.RGBLED
    name: RGB LED Strip
    description: Demo RGB LED Strip
    service: Mqtt
    gpio: # Example GPIO settings for this device
      pins:
        red: 17     # Board 11
        green: 27   # Board 13
        blue: 22    # Board 15
#      active_high: false   # active_high is set to false by default
#      pwm: true           # pwm is set to true by default and necessary for brightness